[deps]
CairoMakie = "13f3f980-e62b-5c42-98c6-ff1f3baf88f0"
PairPlots = "43a3c2be-4208-490b-832a-a21dcd55d7da"
QEDcore = "35dc0263-cb5f-4c33-a114-1d7f54ab753e"
QEDprobing = "fdc9d422-4d58-410b-839e-b42714d9ecda"
QEDprocesses = "46de9c38-1bb3-4547-a1ec-da24d767fdad"
