#
# credits: https://gitlab.com/tkpapp/GitlabJuliaDemo.jl
#

image: julia:latest # image comes from Docker hub

stages:
  - linter
  - test
  - deploy

before_script:
  # workaround for https://github.com/JuliaDocs/Documenter.jl/issues/686
  - apt-get -qq update; apt-get -y install git
  - julia --project=@. -e "import Pkg; Pkg.build()"

runic:
  stage: linter
  script:
    - julia --project=@runic -e 'using Pkg; Pkg.add("Runic")'
    - julia --startup-file=no --project=@runic -e 'using Runic; exit(Runic.main(ARGS))' -- --check --diff --verbose .
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH == "main"

unittest:
  stage: test
  script:
    - julia --project=@. -e 'using Pkg; Pkg.build()'
    - julia --project=@. add_dev_packages.jl
    - julia --project=@. -e 'using Pkg; Pkg.test(coverage=true)'
  coverage: /Test coverage (\d+\.\d+%)/
  after_script:
    - |
      julia -e '
        using Pkg
        Pkg.add("Coverage")
        using Coverage
        coverage = process_folder()
        coverage = merge_coverage_counts(coverage, filter!(
            let prefixes = (joinpath(pwd(), "src", ""),)
                c -> any(p -> startswith(c.filename, p), prefixes)
            end,
            LCOV.readfolder("test")))
        covered_lines, total_lines = get_summary(coverage)
        using Printf
        @printf "Test coverage %.2f%%\n" 100 * covered_lines / total_lines'
  rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event' || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'dev' || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == 'main'

pages:
  stage: deploy
  script:
    - julia --project=docs -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
    - julia --project=docs add_dev_packages.jl
    - julia --project=docs --color=yes docs/make.jl
    - mv docs/build public # move to the directory picked up by Gitlab pages
  artifacts:
    paths:
      - public
  only:
    - main
