name = "QEDprobing"
uuid = "fdc9d422-4d58-410b-839e-b42714d9ecda"
authors = ["Uwe Hernandez Acosta <u.hernandez@hzdr.de"]
version = "1.0.0-DEV"

[deps]
QEDbase = "10e22c08-3ccb-4172-bfcf-7d7aa3d04d93"
QEDcore = "35dc0263-cb5f-4c33-a114-1d7f54ab753e"
QEDprocesses = "46de9c38-1bb3-4547-a1ec-da24d767fdad"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
QEDbase = "0.3.0"
QEDcore = "0.2.0"
QEDprocesses = "0.3.0"
Random = "1.11.0"
SafeTestsets = "0.1.0"
julia = "1.6"

[extras]
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SafeTestsets = "1bc83da4-3b8d-516f-aca4-4fe02f6d838f"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "SafeTestsets", "Random"]
